### ISSUE TITLE
Error parsing Character: TypeError: Cannot read property 'getContent' of undefined

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#165]
I have recently started getting the error below at, or near (not sure if anything is actually missing) , the end of imports on some, but not all, PCs in my world.

06:30:55.748 main.js:1528 DDB Importer | ERR > TypeError: Cannot read property 'getContent' of undefined  
log @ main.js:1528  
error @ main.js:1548  
(anonymous) @ main.js:26254  
async function (async)  
(anonymous) @ main.js:26233  
dispatch @ jquery.min.js:2  
v.handle @ jquery.min.js:2  
06:30:55.750 main.js:1528 DDB Importer | ERR > TypeError: Cannot read property 'getContent' of undefined  
    at loadPacks (https://assets.forge-vtt.com/bazaar/modules/dae/0.8.44/module/migration.js:103:75)  
    at async Object.migrateActorDAESRD (https://assets.forge-vtt.com/bazaar/modules/dae/0.8.44/module/migration.js:130:9)  
    at async migrateActorDAESRD (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.3.12/dist/main.js:2344:3)  
    at async CharacterImport.parseCharacterData (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.3.12/dist/main.js:26817:7)  
    at async HTMLButtonElement.<anonymous> (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.3.12/dist/main.js:26241:13)  
log @ main.js:1528  
error @ main.js:1548  
(anonymous) @ main.js:26255  
async function (async)  
(anonymous) @ main.js:26233  
dispatch @ jquery.min.js:2  
v.handle @ jquery.min.js:2

**Comment by MrPrimate** [comment]
This is a problem with a function provided by the DAE module - as a work around can you try using _Copy Active Effect from DAE Compendiums_ rather than _[Caution] Replace Items using DAE compendiums_

**Comment by MrPrimate** [comment]
This should be resolved as of v2.4.1
