### ISSUE TITLE
 DDB Importer | ERR > TypeError: Cannot read properties of null (reading 'includes')

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#203]
I am receiving the following errors when importing monsters and it seems to stop the monster import on "Updating Zuggtmoy: Madness of Zuggtmoy". I checked my Monster Actor folder, and there is no updating going on in the background.

```
logger.js:62 
       DDB Importer | ERR > TypeError: Cannot read properties of null (reading 'includes')
log @ logger.js:62
error @ logger.js:82
parseCritters @ ddb.js:266
```
```
logger.js:62 
       DDB Importer | ERR > TypeError: Cannot read properties of null (reading 'includes')
    at getLanguages (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.8.9/dist/main.js:9386:29)
    at parseMonster (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.8.9/dist/main.js:11707:40)
    at https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.8.9/dist/main.js:11821:28
    at Array.forEach (<anonymous>)
    at parseMonsters (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.8.9/dist/main.js:11819:15)
    at https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.8.9/dist/main.js:21262:64
log @ logger.js:62
error @ logger.js:82
parseCritters @ ddb.js:267
```
edit: It seems to be getting stuck at the end of item table creation

**Comment by MrPrimate** [comment]
Fixed in v2.8.10. Hopefully.
