### ISSUE TITLE
Failure rendering DDBMuncher

### ISSUE THREAD

**Issue by Eleuis** [MrPrimate/ddb-importer#227]
Foundry Version: 0.8.9 (Build 102)
Module Version: 2.7.7

When clicking on the DDB Muncher button, it throws the following error:

```
foundry.js:2040 Foundry VTT | Rendering DDBMuncher

foundry.js:2013 TypeError: Cannot read properties of undefined (reading 'sources')
[Detected 1 package: ddb-importer]
    at getSourcesLookups (main.js:22871:65)
    at getMuncherSettings (main.js:22632:23)
    at DDBMuncher.getData (main.js:23234:24)
    at DDBMuncher._render (foundry.js:2049:29)
    at B.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:466:22)
    at DDBMuncher.🎁Application.prototype._render#lib-wrapper (listeners.js:110:11)
    at DDBMuncher.🎁Application.prototype._render#0 (libWrapper-wrapper.js:161:52)
    at DDBMuncher.render (foundry.js:2011:9)
    at HTMLDivElement.<anonymous> (main.js:34482:30)
```
The error happens both in the client and in chrome. The rest of the features in the module seem to be working find, including every other import feature.

**Comment by MrPrimate** [comment]
Please can you try updating DDB Importer to the latest version 2.9.30, it sounds like you are a bit out of date with some changes.
