### ISSUE TITLE
API Failure: Only absolute URLs are supported

### ISSUE THREAD

**Issue by macdhollister** [MrPrimate/ddb-importer#228]
When starting foundry, the importer fails to load. Reverting back to `2.9.30` fixes the issue.

Environment:

- Foundry version 9 Build 269
- DnD5e version `1.5.7`
- D&D Beyond Importer version `2.9.31`
- No other Foundry modules enabled
- ddb-proxy `v0.0.15` (working off of `main` on commit `784d33911987e2c978953a7397b59a975ee0cb72` which is the latest as of the writing of this issue)
- `game.settings.get("ddb-importer", "api-endpoint")` --> `http://localhost:3000`
- `game.settings.get("ddb-importer", "custom-proxy")` --> `true`
- Proxy run via both Docker and via `node index.js` and get the same issue either way

Two errors in the console of Foundry
```
logger.js:67 DDB Importer | ERR > API Failure: Unknown error during config loading: TypeError: Only absolute URLs are supported

ddbConfig.js:46 Uncaught (in promise) Unknown error during config loading: TypeError: Only absolute URLs are supported
```

Full stack trace from the proxy when I start my world in Foundry
```
Retrieving ddb config
undefined
Error retrieving DDB Config
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/srv/node_modules/node-fetch/lib/index.js:1327:9)
    at /srv/node_modules/node-fetch/lib/index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (/srv/node_modules/node-fetch/lib/index.js:1437:9)
    at /srv/lookup.js:30:5
    at new Promise (<anonymous>)
    at Object.getConfig (/srv/lookup.js:8:10)
    at /srv/index.js:42:6
    at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/node_modules/express/lib/router/route.js:137:13)
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/srv/node_modules/node-fetch/lib/index.js:1327:9)
    at /srv/node_modules/node-fetch/lib/index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (/srv/node_modules/node-fetch/lib/index.js:1437:9)
    at /srv/lookup.js:30:5
    at new Promise (<anonymous>)
    at Object.getConfig (/srv/lookup.js:8:10)
    at /srv/index.js:42:6
    at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/node_modules/express/lib/router/route.js:137:13)

```

**Comment by MrPrimate** [comment]
v0.0.16 should fix this.
