### ISSUE TITLE
Character Import "This is not a registered game setting"

### ISSUE THREAD

**Issue by cosmylk** [MrPrimate/ddb-importer#243]
```
logger.js:67 DDB Importer | ERR > Error: This is not a registered game setting
log @ logger.js:67
logger.js:65 DDB Importer | ERR > Error during parse: This is not a registered game setting
log @ logger.js:65
logger.js:67 DDB Importer | ERR > JSON Fetch and Parse Error
log @ logger.js:67
logger.js:67 DDB Importer | ERR > Error: This is not a registered game setting
log @ logger.js:67
logger.js:67 DDB Importer | ERR > Error: This is not a registered game setting
    at ClientSettings.get (http://localhost:30000/scripts/foundry.js:2150:42)
    at configureDependencies (http://localhost:30000/modules/ddb-importer/dist/main.js:2558:41)
    at generateExtraEffects (http://localhost:30000/modules/ddb-importer/dist/main.js:3516:58)
    at http://localhost:30000/modules/ddb-importer/dist/main.js:34713:59
    at Array.map (<anonymous>)
    at addExtraEffects (http://localhost:30000/modules/ddb-importer/dist/main.js:34712:49)
    at parseFeatures (http://localhost:30000/modules/ddb-importer/dist/main.js:35828:25)
    at parseJson (http://localhost:30000/modules/ddb-importer/dist/main.js:36505:36)
    at async getCharacterData (http://localhost:30000/modules/ddb-importer/dist/main.js:38192:25)
    at async HTMLButtonElement.<anonymous> (http://localhost:30000/modules/ddb-importer/dist/main.js:38523:33)
log @ logger.js:67
logger.js:67 DDB Importer | ERR > Error: This is not a registered game setting
log @ logger.js:67
logger.js:67 DDB Importer | ERR > Error: This is not a registered game setting
    at ClientSettings.get (http://localhost:30000/scripts/foundry.js:2150:42)
    at configureDependencies (http://localhost:30000/modules/ddb-importer/dist/main.js:2558:41)
    at generateExtraEffects (http://localhost:30000/modules/ddb-importer/dist/main.js:3516:58)
    at http://localhost:30000/modules/ddb-importer/dist/main.js:34713:59
    at Array.map (<anonymous>)
    at addExtraEffects (http://localhost:30000/modules/ddb-importer/dist/main.js:34712:49)
    at parseFeatures (http://localhost:30000/modules/ddb-importer/dist/main.js:35828:25)
    at parseJson (http://localhost:30000/modules/ddb-importer/dist/main.js:36505:36)
    at async getCharacterData (http://localhost:30000/modules/ddb-importer/dist/main.js:38192:25)
    at async HTMLButtonElement.<anonymous> (http://localhost:30000/modules/ddb-importer/dist/main.js:38523:33)
```

**Comment by MrPrimate** [comment]
This was convenient effects on an old version if anyone else comes across this issue. Uninstall and reinstall it.
