### ISSUE TITLE
Foundry V10 Error: Setting Model Validation Errors

### ISSUE THREAD

**Issue by AlanDNelson** [MrPrimate/ddb-importer#258]
I get this error in both a migrated World... and a brand new World with just the D&D Beyond Importer module enabled.

```
ERROR
commons.js:3605 Uncaught (in promise) Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[Detected 1 package: ddb-importer]
    at SchemaField._validateType (commons.js:3605:15)
    at SchemaField.validate (commons.js:3332:37)
    at Setting.validate (commons.js:4969:35)
    at new DataModel (commons.js:4746:26)
    at new Document (commons.js:5268:3)
    at new BaseSetting (commons.js:9242:3)
    at new ClientDocumentMixin (foundry.js:12789:5)
    at new Setting (foundry.js:20808:1)
    at ClientSettings.get (foundry.js:2660:21)
    at createIfNotExists (checkCompendiums.js:12:1)
    at checkCompendiums.js:50:1
    at Array.forEach (<anonymous>)
    at checkCompendiums (checkCompendiums.js:49:5)
    at Object.onceReady [as fn] (hooks.js:49:3)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at Game.setupGame (foundry.js:7621:11)
    at async Game._initializeGameView (foundry.js:8667:5)
    at async Game.initialize (foundry.js:7482:5)
```
    
```
    When I press the D&D Beyond button from a character sheet, nothing happens.
    In the console:

WARNING
    Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1232:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:6101:14)
    at get data [as data] (commons.js:6001:24)
    at CharacterImport.migrateMetadata (import.js:239:1)
    at new CharacterImport (import.js:223:1)
    at HTMLButtonElement.<anonymous> (registerSheets.js:89:1)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
```
```

ERROR
TypeError: Cannot read properties of undefined (reading 'version')
[Detected 1 package: ddb-importer]
    at getCharacterImportSettings (settings.js:126:34)
    at CharacterImport.getData (import.js:418:28)
    at CharacterImport._render (foundry.js:4849:29)
    at CharacterImport._render (foundry.js:5574:17)
    at CharacterImport.render (foundry.js:4808:10)
    at HTMLButtonElement.<anonymous> (registerSheets.js:90:1)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
```

**Comment by MrPrimate** [comment]
V10 of Foundry is not yet supported in the publicly available module.

**Comment by AlanDNelson** [comment]
Oh... no problem.  I thought the release was for testing.

Thanks for your work!

     - Alan

**Comment by MrPrimate** [comment]
v10 version is now live.
