### ISSUE TITLE
Cannot click into "Core Setup" in latest update 3.1.7

### ISSUE THREAD

**Issue by themantheycalljames** [MrPrimate/ddb-importer#270]
Going into Configure Setting I cannot click the "Core Setup" button. I disabled all other modules just to double check there wasn't a conflict.

**Comment by themantheycalljames** [comment]
@MrPrimate already tried that still doesn't open.

Also some console logs if this helps when clicking the button

Secrets.js:81          POST http://localhost:3000/proxy/auth net::ERR_CONNECTION_REFUSED
(anonymous) @ Secrets.js:81
checkCobalt @ Secrets.js:80
getData @ Settings.js:325
_render @ foundry.js:5067
_render @ foundry.js:5780
render @ foundry.js:5026
_onClickSubmenu @ foundry.js:71156
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
logger.js:76 DDB Importer | ERR > Cobalt cookie check error
log @ logger.js:76
error @ logger.js:96
(anonymous) @ Secrets.js:92
Promise.catch (async)
(anonymous) @ Secrets.js:91
checkCobalt @ Secrets.js:80
getData @ Settings.js:325
_render @ foundry.js:5067
_render @ foundry.js:5780
render @ foundry.js:5026
_onClickSubmenu @ foundry.js:71156
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
logger.js:76 DDB Importer | ERR > TypeError: Failed to fetch
log @ logger.js:76
error @ logger.js:96
(anonymous) @ Secrets.js:93
Promise.catch (async)
(anonymous) @ Secrets.js:91
checkCobalt @ Secrets.js:80
getData @ Settings.js:325
_render @ foundry.js:5067
_render @ foundry.js:5780
render @ foundry.js:5026
_onClickSubmenu @ foundry.js:71156
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
logger.js:76 DDB Importer | ERR > TypeError: Failed to fetch
    at http://localhost:30000/modules/ddb-importer/dist/main.js:19859:5
    at new Promise (<anonymous>)
    at checkCobalt (http://localhost:30000/modules/ddb-importer/dist/main.js:19858:10)
    at DDBSetup.getData (http://localhost:30000/modules/ddb-importer/dist/main.js:32457:32)
    at DDBSetup._render (http://localhost:30000/scripts/foundry.js:5067:29)
    at DDBSetup._render (http://localhost:30000/scripts/foundry.js:5780:17)
    at DDBSetup.render (http://localhost:30000/scripts/foundry.js:5026:10)
    at SettingsConfig._onClickSubmenu (http://localhost:30000/scripts/foundry.js:71156:16)
    at HTMLButtonElement.dispatch (http://localhost:30000/scripts/jquery.min.js:2:43064)
    at y.handle (http://localhost:30000/scripts/jquery.min.js:2:41048)
log @ logger.js:76
error @ logger.js:96
(anonymous) @ Secrets.js:94
Promise.catch (async)
(anonymous) @ Secrets.js:91
checkCobalt @ Secrets.js:80
getData @ Settings.js:325
_render @ foundry.js:5067
_render @ foundry.js:5780
render @ foundry.js:5026
_onClickSubmenu @ foundry.js:71156
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 TypeError: Failed to fetch
    at Secrets.js:81:1
    at new Promise (<anonymous>)
    at checkCobalt (Secrets.js:80:1)
    at DDBSetup.getData (Settings.js:325:32)
    at DDBSetup._render (foundry.js:5067:29)
    at DDBSetup._render (foundry.js:5780:17)
    at DDBSetup.render (foundry.js:5026:10)
    at SettingsConfig._onClickSubmenu (foundry.js:71156:16)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by themantheycalljames** [comment]
@MrPrimate ok not sure why it happened cannot seem to recreate this now but I clicked "reset DBB Importer Settings" and then i was able to click the "Core setup" button. Also after this I had to re-attach the Compendiums to the right ones. From what I can tell this all happened after the lastest v10 b286 core update and updating your module to the latest 3.1.7

**Comment by MrPrimate** [comment]
This looks like your running a local ddb-proxy. Please make sure that is running correctly, or switch back to mine, as mentioned in the ddb-proxy readme, I don't provide support for that.
