### ISSUE TITLE
Html Description breaks custom items in Update DND Beyond

### ISSUE THREAD

**Issue by matthewbstroud** [MrPrimate/ddb-importer#310]
[error.txt](https://github.com/MrPrimate/ddb-importer/files/10928091/error.txt)
**Describe the bug**
When uploading a custom item with any html tags, you will get an error.
**To Reproduce**
1. Create a custom item in Foundry (or select an SRD item)
2. Make sure the item has formatted description.
3. Drag the item into the inventory of a player character.
4. Use the Update DND Beyond feature

This is Foundry v9.23.
Browser was Chrome.
DNDBeyond Importer v2.9.67

**Comment by matthewbstroud** [comment]
`[
    "Update failed for Stuart Finn:",
    {
        "url": "https://proxy.ddb.mrprimate.co.uk/proxy/update/custom/item",
        "path": "custom/item",
        "errorData": {
            "success": false,
            "message": "Unknown error during character update: ",
            "data": {
                "id": 0,
                "success": false,
                "message": "The parameters provided are invalid.",
                "data": [
                    "Invalid parameter: description"
                ],
                "pagination": null
            }
        },
        "bodyContent": {
            "itemState": "NEW",
            "customValues": {
                "characterId": 83435710,
                "containerEntityId": 83435710,
                "containerEntityTypeId": 1581111423,
                "name": "Spell Scroll: Charm Person",
                "description": "<p>A spell scroll bears the words of a single spell, written in a mystical cipher. If the spell is on your class's spell list, you can read the scroll and cast its spell without providing any material components. Otherwise, the scroll is unintelligible. Casting the spell by reading the scroll requires the spell's normal casting time. Once the spell is cast, the words on the scroll fade, and it crumbles to dust. If the casting is interrupted, the scroll is not lost.</p><hr /><h3>Charm Person (Level 1)</h3><hr /><p>You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you.</p>\n        <p><strong>At Higher Levels.</strong> When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.</p><hr /><h3>Scroll Details</h3><hr />\n<p>If the spell is on your class's spell list but of a higher level than you can normally cast, you must make a DC 11 ability check using your spellcasting ability to determine whether you cast it successfully. On a failed check, the spell disappears from the scroll with no other effect.</p>\n<p>The level of the spell on the scroll determines the spell's saving throw DC and attack bonus, as well as the scroll's rarity.</p>\n<p><strong>Save DC</strong>: 13<br /><strong>Attack Bonus</strong>: +5.</p>\n<p>A wizard spell on a spell scroll can be copied just as spells in spellbooks can be copied. When a spell is copied from a spell scroll, the copier must succeed on a DC 11 Intelligence (Arcana) check. If the check succeeds, the spell is successfully copied. Whether the check succeeds or fails, the spell scroll is destroyed.</p>",
                "quantity": 1,
                "cost": null,
                "weight": 0
            }
        },
        "characterId": "83435710",
        "dynamicSync": false,
        "flavor": {
            "name": "Spell Scroll: Charm Person"
        }
    }
]`

**Comment by matthewbstroud** [comment]
[
    "Update failed for Stuart Finn:",
    {
        "url": "https://proxy.ddb.mrprimate.co.uk/proxy/update/custom/item",
        "path": "custom/item",
        "errorData": {
            "success": false,
            "message": "Unknown error during character update: ",
            "data": {
                "id": 0,
                "success": false,
                "message": "The parameters provided are invalid.",
                "data": [
                    "Invalid parameter: description"
                ],
                "pagination": null
            }
        },
        "bodyContent": {
            "itemState": "NEW",
            "customValues": {
                "characterId": 83435710,
                "containerEntityId": 83435710,
                "containerEntityTypeId": 1581111423,
                "name": "Spell Scroll: Charm Person",
                "description": "<p>A spell scroll bears the words of a single spell, written in a mystical cipher. If the spell is on your class's spell list, you can read the scroll and cast its spell without providing any material components. Otherwise, the scroll is unintelligible. Casting the spell by reading the scroll requires the spell's normal casting time. Once the spell is cast, the words on the scroll fade, and it crumbles to dust. If the casting is interrupted, the scroll is not lost.</p><hr /><h3>Charm Person (Level 1)</h3><hr /><p>You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you.</p>\n        <p><strong>At Higher Levels.</strong> When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.</p><hr /><h3>Scroll Details</h3><hr />\n<p>If the spell is on your class's spell list but of a higher level than you can normally cast, you must make a DC 11 ability check using your spellcasting ability to determine whether you cast it successfully. On a failed check, the spell disappears from the scroll with no other effect.</p>\n<p>The level of the spell on the scroll determines the spell's saving throw DC and attack bonus, as well as the scroll's rarity.</p>\n<p><strong>Save DC</strong>: 13<br /><strong>Attack Bonus</strong>: +5.</p>\n<p>A wizard spell on a spell scroll can be copied just as spells in spellbooks can be copied. When a spell is copied from a spell scroll, the copier must succeed on a DC 11 Intelligence (Arcana) check. If the check succeeds, the spell is successfully copied. Whether the check succeeds or fails, the spell scroll is destroyed.</p>",
                "quantity": 1,
                "cost": null,
                "weight": 0
            }
        },
        "characterId": "83435710",
        "dynamicSync": false,
        "flavor": {
            "name": "Spell Scroll: Charm Person"
        }
    }
]

**Comment by matthewbstroud** [comment]
I attached the error log, but now I am having trouble reproducing it.

**Comment by FeistyMango** [comment]
I was running into this as well. However, it is not html that casues it. Intially, I thought it might be special unicode characters or some unescaped character. However, I did a binary style truncate search on a string that was blowing up coming back with the error `Invalid parameter for Description` and after doing a binary truncate style-search looking forward what portion of the string causes the exception I discovered that it wasn't the contents of the string. It's that DndBeyond only supports a maximize custom Description field of 2056 characters. If you go into a DndBeyond sheet and enter any string that is 2057 you'll be able to reproduce the unhandled exception in the website as well.

Suggestion:
Truncate any description to 2056 and emit a useful console.warn() for the given item indicating that it had to be truncated.

**Comment by matthewbstroud** [comment]
Thanks for sharing.  I will make a macro to truncate strings in the players
inventory when they get the error.

**Comment by MrPrimate** [comment]
It should strip the html out already, however, I have found that compendium style links for conditions or to other items also break it.

**Comment by matthewbstroud** [comment]
@MrPrimate that might be what I experienced.

**Comment by matthewbstroud** [comment]
Can you provide an example?

**Comment by FeistyMango** [comment]
Sure, I also posted a bug report on DnDBeyond here about the issue hoping they'll just increase the max length they support - https://www.dndbeyond.com/forums/d-d-beyond-general/bugs-support/166788-custom-item-descriptions-that-exceed-2056
![image](https://user-images.githubusercontent.com/3461388/224517605-317a695d-e981-4c7f-92e5-2e883f413d29.png)

Error  Output:
```
foundry.js:59187 Update failed: (Lorelei Corvus) Unknown error during character update:  (see console log (F12) for more details)
fetch @ foundry.js:59187
notify @ foundry.js:59114
error @ foundry.js:59150
(anonymous) @ character.js:106
Promise.then (async)
(anonymous) @ character.js:94
updateCharacterCall @ character.js:84
addDDBCustomItems @ character.js:595
addDDBEquipment @ character.js:620
await in addDDBEquipment (async)
addEquipment @ character.js:716
updateDDBCharacter @ character.js:1106
VM3407:62 Sync Character | Error | [object Object] TypeError: Cannot read properties of undefined (reading '0')
    at character.js:596:1
    at async Promise.all (index 0)
    at async addDDBEquipment (character.js:620:1)
    at async Object.updateDDBCharacter (character.js:1106:1)
    at async eval (eval at executeScript (lib.js:175:13), <anonymous>:53:9)
    at async Object.executeMacroArr (api.js:38:10)
    
```


Enter this string you will get the exception, remove the last letter and it will succeed:

```hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh2057```

**Comment by FeistyMango** [comment]
![image](https://user-images.githubusercontent.com/3461388/224517633-bfec31f8-6705-4332-bf6f-607a9a7e3f72.png)

**Comment by MrPrimate** [comment]
> Can you provide an example?

It might look something like:
```html
This item is a collection of 400 @UUID[Compendium.world.ddb-mrprimate-ddb-items.XMPkeg9CO8tdtfAG]{Herbalism Kit's}
```

**Comment by MrPrimate** [comment]
A trim fix will be in the next release

**Comment by MrPrimate** [comment]
Fix in v3.4.0

**Comment by matthewbstroud** [comment]
@MrPrimate will this only be fixed in the v10 version?

**Comment by MrPrimate** [comment]
@matthewbstroud I wasn't going to, but I'll see if I can backport the fixes for you tomorrow.

**Comment by matthewbstroud** [comment]
I haven't actually found a way to _consistently_ reproduce in v9.  I had thought about just writing a macro that pre-scrubs all descriptions.  I wanted v10 to be out for a year before switching...

**Comment by MrPrimate** [comment]
@matthewbstroud released.

**Comment by matthewbstroud** [comment]
Thank you!

**Comment by matthewbstroud** [comment]
Will this propagate to the forge?  Or will I just need to install by manifest?
![image](https://user-images.githubusercontent.com/17620888/228062700-5cba4b0b-f422-4925-b571-1798defe9a1f.png)

**Comment by MrPrimate** [comment]
Should do, but there might be some oddities with the forge and versions here, so might be worth a manual install
