### ISSUE TITLE
ERROR Report: Import

### ISSUE THREAD

**Issue by swedax94** [MrPrimate/ddb-importer#441]
I tried to import this Charakter: 
[www.dndbeyond.com/characters/114944533/QkBKBw](url)

But it wouldn't import and gives this ERROR. How can I fix this?
Tried many things (untick things for example) but it will be the same Error again and again.
![image](https://github.com/MrPrimate/ddb-importer/assets/9264745/1e0da03b-7716-43bc-9c17-b024dafe9b93)

In the Developer Console it seams to give me:
`logger.js:83 DDB Importer | ERR > TypeError: m.replace is not a function
    at FieldMapping.convertSource [as converter] (http://dnd.xxxx.de:31000/modules/FoundryVTT-dnd5e-DE/dnd5e-de.js:546:46)
    at FieldMapping.translate (http://dnd.xxxx.de:31000/modules/babele/babele.js:1006:26)
    at FieldMapping.map (http://dnd.xxxx.de:31000/modules/babele/babele.js:989:28)
    at http://dnd.xxxx.de:31000/modules/babele/babele.js:1072:62
    at Array.reduce (<anonymous>)
    at CompendiumMapping.map (http:/dnd.xxxx.de:31000/modules/babele/babele.js:1072:28)
    at TranslatedCompendium.translate (http://dnd.xxxx.de:31000/modules/babele/babele.js:1235:43)
    at Babele.translate (http://dnd.xxxx.de:31000/modules/babele/babele.js:763:19)
    at http://dnd.xxxx.de:31000/modules/babele/babele.js:78:54
    at Array.map (<anonymous>)
    at 🎁ClientDatabaseBackend.prototype._getDocuments#babele (http://dnd.xxxx.de:31000/modules/babele/babele.js:77:27)
    at async CompendiumCollection.getDocuments (http://dnd.xxxx.de:31000/scripts/foundry.js:16280:23)
    at async CompendiumCollection.getDocument (http://dnd.xxxx.de:31000/scripts/foundry.js:16252:23)
    at async addSRDAdvancements (http://dnd.xxxx.de:31000/modules/ddb-importer/dist/main.js:30226:22)
    at async getClasses (http://dnd.xxxx.de:31000/modules/ddb-importer/dist/main.js:30377:32)
    at async DDBCharacter._parseCharacter (http://dnd.xxxx.de:31000/modules/ddb-importer/dist/main.js:27328:26)
    at async DDBCharacter.getCharacterData (http://dnd.xxxx.de:31000/modules/ddb-importer/di`

**Comment by MrPrimate** [comment]
This is Babel module breaking the import
