### ISSUE TITLE
Error when importing Spells, items, Monsters

### ISSUE THREAD

**Issue by pefcs** [MrPrimate/ddb-importer#463]
**Describe the bug**
Created a new world and getting error when trying to munch spells, items, monsters. In my existing world it works well

**To Reproduce**
1. Create a new world
2. Configure DDB importer
3. Goto DDB muncher
4. Select spells/items/monsters
5. Press munch button
6. Error in console - nothing is shown in GUI, but also nothing is happening

**Expected behavior**
Munching works

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/118229534/b232c159-3c66-4e16-847f-7e1394cb3872)

**Environment:**
 - Browser: Chrome
 - Foundry Version [11.315]
 - 5e System Version [3.0.3]
 - Module Version [4.0.12]
 - Does this behaviour occur with other modules disabled: Turned off every other modules. Only DDB Importer is enabled

 - Running the import as Game Master
 - Details of any errors in the browser console (press F12).

logger.js:84 DDB Importer | ERR > TypeError: Cannot convert undefined or null to object
log	@	logger.js:84

logger.js:84 DDB Importer | ERR > TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at http://localhost:30000/modules/ddb-importer/dist/main.js:24197:70
    at Array.find (<anonymous>)
    at NameMatcher.looseItemNameMatch (http://localhost:30000/modules/ddb-importer/dist/main.js:24193:30)
    at http://localhost:30000/modules/ddb-importer/dist/main.js:22803:107
    at Array.map (<anonymous>)
    at Iconizer.copySRDIcons (http://localhost:30000/modules/ddb-importer/dist/main.js:22797:28)
    at async Iconizer.updateIcons (http://localhost:30000/modules/ddb-importer/dist/main.js:23131:15)
    at async DDBItemImporter.iconAdditions (http://localhost:30000/modules/ddb-importer/dist/main.js:20502:22)
    at async DDBItemImporter.buildHandler (http://localhost:30000/modules/ddb-importer/dist/main.js:20512:5)

**Comment by MrPrimate** [comment]
Fixed in v4.0.13
