### ISSUE TITLE
Error processing Character: TypeError: Cannot add property pool, object is not extensible l

### ISSUE THREAD

**Issue by Melfarion90** [MrPrimate/ddb-importer#474]
Getting "Error processing Character: TypeError: Cannot add property pool, object is not extensible" when trying to upload a specific Character (https://www.dndbeyond.com/characters/97399969) all other chars imported just fine.
Somehow it seems related with the Drow race.
When using a wood elf first for example, the character imports fine. When changing it to Drow the error occurs,
Also when trying to change back to another race the error still occurs.

Devconsole Log:
logger.js:82 DDB Importer | ERR > Error during parse: Cannot add property pool, object is not extensible
logger.js:84 DDB Importer | ERR > JSON Fetch and Parse Error
logger.js:84 DDB Importer | ERR > TypeError: Cannot add property pool, object is not extensible
logger.js:84 DDB Importer | ERR > TypeError: Cannot add property pool, object is not extensible
    at _mergeInsert (http://localhost:30000/scripts/commons.js:2787:17)
    at mergeObject (http://localhost:30000/scripts/commons.js:2761:12)
    at #updateField (http://localhost:30000/scripts/commons.js:7354:9)
    at #updateData (http://localhost:30000/scripts/commons.js:7302:26)
    at TraitAdvancement.updateSource (http://localhost:30000/scripts/commons.js:7258:30)
    at TraitAdvancement.updateSource (http://localhost:30000/systems/dnd5e/dnd5e.mjs:1670:11)
    at AdvancementHelper.getExpertiseAdvancement (http://localhost:30000/modules/ddb-importer/dist/main.js:35082:17)
    at DDBClass._generateExpertiseAdvancements (http://localhost:30000/modules/ddb-importer/dist/main.js:31098:50)
    at DDBClass._generateCommonAdvancements (http://localhost:30000/modules/ddb-importer/dist/main.js:31253:10)
    at async DDBClass.generateFromCharacter (http://localhost:30000/modules/ddb-importer/dist/main.js:31282:5)
    at async CharacterClassFactory.processCharacter (http://localhost:30000/modules/ddb-importer/dist/main.js:31532:7)
    at async DDBCharacter._parseCharacter (http://localhost:30000/modules/ddb-importer/dist/main.js:32812:26)
    at async DDBCharacter.getCharacterData (http://localhost:30000/modules/ddb-importer/dist/main.js:32715:9)
    at async HTMLButtonElement.<anonymous> (http://localhost:30000/modules/ddb-importer/dist/main.js:56109:11)
logger.js:84 DDB Importer | ERR > TypeError: Cannot add property pool, object is not extensible
logger.js:84 DDB Importer | ERR > TypeError: Cannot add property pool, object is not extensible
    at _mergeInsert (http://localhost:30000/scripts/commons.js:2787:17)
    at mergeObject (http://localhost:30000/scripts/commons.js:2761:12)
    at #updateField (http://localhost:30000/scripts/commons.js:7354:9)
    at #updateData (http://localhost:30000/scripts/commons.js:7302:26)
    at TraitAdvancement.updateSource (http://localhost:30000/scripts/commons.js:7258:30)
    at TraitAdvancement.updateSource (http://localhost:30000/systems/dnd5e/dnd5e.mjs:1670:11)
    at AdvancementHelper.getExpertiseAdvancement (http://localhost:30000/modules/ddb-importer/dist/main.js:35082:17)
    at DDBClass._generateExpertiseAdvancements (http://localhost:30000/modules/ddb-importer/dist/main.js:31098:50)
    at DDBClass._generateCommonAdvancements (http://localhost:30000/modules/ddb-importer/dist/main.js:31253:10)
    at async DDBClass.generateFromCharacter (http://localhost:30000/modules/ddb-importer/dist/main.js:31282:5)
    at async CharacterClassFactory.processCharacter (http://localhost:30000/modules/ddb-importer/dist/main.js:31532:7)
    at async DDBCharacter._parseCharacter (http://localhost:30000/modules/ddb-importer/dist/main.js:32812:26)
    at async DDBCharacter.getCharacterData (http://localhost:30000/modules/ddb-importer/dist/main.js:32715:9)
    at async HTMLButtonElement.<anonymous> (http://localhost:30000/modules/ddb-importer/dist/main.js:56109:11)
logger.js:82 DDB Importer | ERR > Failure 
{ddbCharacter: DDBCharacter, result: {…}}
﻿
Foundry Version 11.315
DnD 5e 3.1.0
DDBImporter 5.01

**Comment by MrPrimate** [comment]
DDB Importer does not support D&D version 3.1 yet, please give module authors time to upgrade.

**Comment by MrPrimate** [comment]
This is resolved in v5.1.0
