### ISSUE TITLE
Importing spells into a new world fails

### ISSUE THREAD

**Issue by mcrumm** [MrPrimate/ddb-importer#488]
**Describe the bug**
Importing spells into a new world fails with only a browser console error.

**To Reproduce**
1. Go to DDB Muncher
2. Click on Spells
3. Click on Spell Munch
4. Note that no error is reported in the UI. The last text rendered is "Parsing spell data."

**Expected behavior**
Spells are munched in the usual way :)

**Environment:**
 - Browser Chrome
 - Foundry Version 11.315
 - 5e System Version 3.2.0
 - Module Version 5.2.1
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

Console error logs:

```
logger.js:70 DDB Importer | INFO > Munching spells!
logger.js:77 DDB Importer | WARN > Midi-QOL needs to be installed for effects
log @ logger.js:77
warn @ logger.js:121
configureDependencies @ DDBMacros.js:84
parseSpells @ spells.js:83
await in parseSpells (async)
parseSpells @ DDBMuncher.js:282
await in parseSpells (async)
(anonymous) @ DDBMuncher.js:89
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
logger.js:84 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'namePostfix')
log @ logger.js:84
error @ logger.js:125
parseSpells @ DDBMuncher.js:288
await in parseSpells (async)
(anonymous) @ DDBMuncher.js:89
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
logger.js:84 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'namePostfix')
    at parseSpell (https://my-server/modules/ddb-importer/dist/main.js:44361:46)
    at https://my-server/modules/ddb-importer/dist/main.js:28150:46
    at Array.map (<anonymous>)
    at getSpells (https://my-server/modules/ddb-importer/dist/main.js:28137:6)
    at parseSpells (https://my-server/modules/ddb-importer/dist/main.js:28296:27)
    at async DDBMuncher.parseSpells (https://my-server/modules/ddb-importer/dist/main.js:4418:7)
log @ logger.js:84
error @ logger.js:125
parseSpells @ DDBMuncher.js:289
await in parseSpells (async)
(anonymous) @ DDBMuncher.js:89
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

I think the issue occurs here:

- https://github.com/MrPrimate/ddb-importer/blob/e3c5a37a8bf7660fdcdb0d9d615fb50c2d85b1a5/src/parser/spells/getGenericSpells.js#L29

**Comment by MrPrimate** [comment]
Resolved

**Comment by mcrumm** [comment]
Thank you!!! My import was successful :)
