### ISSUE TITLE
[BUG] importing Cleric doesn't work properly. Abilities and spells undefined.

### ISSUE THREAD

**Issue by SirAron111** [MrPrimate/ddb-importer#493]
**Describe the bug**
I can import all other characters just fine. But the Cleric seems buggy. It worked all year before, but just recently when I import, all his spell are undefined and his ability are no longer linked to the sheet's resources. It is throwing errors when he long rests as well. Stuff about value undefined.

**To Reproduce**
1. import a cleric with spells and higher lvl.
2. issue should happen, at least it does for me.

**Expected behavior**
A normal importing with no issues like the other classes.

**Screenshots**
.
![Unbenannt](https://github.com/MrPrimate/ddb-importer/assets/39855956/eb92996b-c2fb-45cc-9542-1cf4e200f1d3)
![Unbenan2nt](https://github.com/MrPrimate/ddb-importer/assets/39855956/b17cda1b-56ec-411a-891e-c8c061055d3c)

**Environment:**
 - Browser [Firefox]
 - Foundry Version [V11]
 - 5e System Version [3.2.0]
 - Module Version [most recent as of this post, not sure about number]
 - Does this behaviour occur with other modules disabled: Yes/No (Find The Culprit module can help with this)
 yes even with other modules turned off.

**Additional context**
There is this:

foundry.js:93012 Foundry VTT | Delaying load of sound assets/audio/Ambience/Travel/The_Adventure_BeginsInstrumental.ogg until after first user gesture
DAEdnd5e.js:1252 Could not prepare data  Rohan Natalis TypeError: Cannot read properties of null (reading 'includes')
    at EquipmentData.prepareFinalActivatedEffectData (activated-effect.mjs:166:93)
    at EquipmentData.prepareFinalData (equipment.mjs:165:10)
    at Item5e.prepareFinalAttributes (item.mjs:669:33)
    at actor.mjs:149:37
    at EmbeddedCollection.forEach (commons.js:4213:9)
    at Actor5e.prepareData (actor.mjs:149:16)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Actor5e.prepareDerivedResources (module.js:142:5)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at Actor5e.prepareData (DAEdnd5e.js:1230:9)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at Actor5e.actorPrepareData (patching.js:904:3)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Actor.documentClass.prototype.prepareData#0 (libWrapper-wrapper.js:189:20)
    at Actor5e.prepareData (automation.mjs:159:19)
    at Actor5e._safePrepareData (foundry.js:14187:14)
    at Game.initializeDocuments (foundry.js:8796:18)
    at Game.setupGame (foundry.js:8706:10)
    at async Game._initializeGameView (foundry.js:9990:5)
prepareData @ DAEdnd5e.js:1252
module.js:19 link-item-resource-5e | Setting up Link Item and Resource DnD5e
messages.mjs:10 Arbron's Improved HP Bar | Loading HP bar for Dungeons & Dragons Fifth Edition
dae.js:21 dae |  Patching Roll.replaceFormulaData
dae.js:21 dae |  Patching ActiveEffect.isTemporary
midi-qol.js:25 midi-qol |  Vision patching -  disabled

and this about the char in the log

activeLighting.js:452 ATE | Going to update token qRE2HboF9DwAR4Ts Object
DAEdnd5e.js:1252 Could not prepare data  Rohan Natalis TypeError: Cannot read properties of null (reading 'includes')
    at EquipmentData.prepareFinalActivatedEffectData (activated-effect.mjs:166:93)
    at EquipmentData.prepareFinalData (equipment.mjs:165:10)
    at Item5e.prepareFinalAttributes (item.mjs:669:33)
    at actor.mjs:149:37
    at EmbeddedCollection.forEach (commons.js:4213:9)
    at Actor5e.prepareData (actor.mjs:149:16)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Actor5e.prepareDerivedResources (module.js:142:5)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at Actor5e.prepareData (DAEdnd5e.js:1230:9)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at Actor5e.actorPrepareData (patching.js:904:3)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Actor.documentClass.prototype.prepareData#0 (libWrapper-wrapper.js:189:20)
    at Actor5e.prepareData (automation.mjs:159:19)
    at Actor5e._safePrepareData (foundry.js:14187:14)
    at Actor5e._initialize (foundry.js:14015:19)
    at Actor5e.reset (commons.js:7101:12)
    at Actor5e._onUpdateDescendantDocuments (foundry.js:19169:84)
    at Actor5e._onUpdateDescendantDocuments (actor.mjs:3289:11)
    at Actor5e._dispatchDescendantDocumentEvents (foundry.js:14405:10)
    at Item5e._dispatchDescendantDocumentEvents (foundry.js:14425:14)
    at #handleUpdateDocuments (foundry.js:13715:26)
    at async ActiveEffect5e.updateDocuments (commons.js:8001:23)
    at async ActiveEffect5e.update (commons.js:8098:23)
    at async DAEActiveEffectConfig._updateObject (DAEActiveEffectConfig.js:343:9)
    at async DAEActiveEffectConfig._onSubmit (foundry.js:6626:7)
prepareData @ DAEdnd5e.js:1252
DAEdnd5e.js:1252 Could not prepare data  Rohan Natalis TypeError: Cannot read properties of null (reading 'includes')
    at EquipmentData.prepareFinalActivatedEffectData (activated-effect.mjs:166:93)
    at EquipmentData.prepareFinalData (equipment.mjs:165:10)
    at Item5e.prepareFinalAttributes (item.mjs:669:33)
    at actor.mjs:149:37
    at EmbeddedCollection.forEach (commons.js:4213:9)
    at Actor5e.prepareData (actor.mjs:149:16)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Actor5e.prepareDerivedResources (module.js:142:5)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at Actor5e.prepareData (DAEdnd5e.js:1230:9)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at Actor5e.actorPrepareData (patching.js:904:3)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Actor.documentClass.prototype.prepareData#0 (libWrapper-wrapper.js:189:20)
    at Actor5e.prepareData (automation.mjs:159:19)
    at Actor5e._safePrepareData (foundry.js:14187:14)
    at Actor5e._initialize (foundry.js:14015:19)
    at Actor5e.updateSource (commons.js:7271:35)
    at #postUpdateDocumentCallbacks (foundry.js:13745:11)
    at #handleUpdateDocuments (foundry.js:13709:73)
prepareData @ DAEdnd5e.js:1252
DAEdnd5e.js:1252 Could not prepare data  Rohan Natalis TypeError: Cannot read properties of null (reading 'includes')
    at EquipmentData.prepareFinalActivatedEffectData (activated-effect.mjs:166:93)
    at EquipmentData.prepareFinalData (equipment.mjs:165:10)
    at Item5e.prepareFinalAttributes (item.mjs:669:33)
    at actor.mjs:149:37
    at EmbeddedCollection.forEach (commons.js:4213:9)
    at Actor5e.prepareData (actor.mjs:149:16)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Actor5e.prepareDerivedResources (module.js:142:5)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at Actor5e.prepareData (DAEdnd5e.js:1230:9)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at Actor5e.actorPrepareData (patching.js:904:3)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Actor.documentClass.prototype.prepareData#0 (libWrapper-wrapper.js:189:20)
    at Actor5e.prepareData (automation.mjs:159:19)
    at Actor5e._safePrepareData (foundry.js:14187:14)
    at Actor5e._initialize (foundry.js:14015:19)
    at Actor5e.updateSource (commons.js:7271:35)
    at #postUpdateDocumentCallbacks (foundry.js:13745:11)
    at #handleUpdateDocuments (foundry.js:13709:73)
prepareData @ DAEdnd5e.js:1252
foundry.js:5802 Foundry VTT | Rendering ActorSensesConfig

**Comment by MrPrimate** [comment]
Please try with all other modules disabled, and find the exact module version, and foundry version. All these errors are from other modules.

If this still persists with ALL other modules disabled, please also provide a public character url.

**Comment by SirAron111** [comment]
www.dndbeyond.com/characters/92388376/HPuvYs

Seems to still be there without other modules. Not sure why it just happens to this character. The others are fine when imported.

**Comment by MrPrimate** [comment]
This imports for me correctly here, please can you grab screenshots of the error messages when you import with no other modules enabled.

**Comment by SirAron111** [comment]
it seems when i import him as a new actor it works flawlessly. its just when i try to update/ overwrite the existing one (given that he has additional things like items and other things added in the vtt) not sure what log i would need to see the error. as there is no error popping up only when i try to long rest him afterward.

**Comment by MrPrimate** [comment]
It's almost certainly some of the "items and things" that have been added to the actor that is breaking long rest.

If the errors don't appear when importing into a new actor, it's a module or something on the actor causing problems

**Comment by SirAron111** [comment]
Ohh my god you were right. It was an item that broke both the long rest and the import.
It was the Dust of Deliciousness.
How the fuck does that even work. 
![Unbenannt](https://github.com/MrPrimate/ddb-importer/assets/39855956/b68bf963-04df-444c-a93c-d0e3206362e4)
![Unbenanntt](https://github.com/MrPrimate/ddb-importer/assets/39855956/a7868854-ac12-4d93-9f4b-0902fc4e33f6)
and you know what it was. It was the fact that the item use field was referencing nothing. Because when it changed, it to this.
It worked again.
![Unbenannttt](https://github.com/MrPrimate/ddb-importer/assets/39855956/07295ebb-5dc8-4287-ad36-ee8d89e0805d)
made a copy of the actor. Deleted every item one by one and then did an import and after deleting the dust it worked. So I looked at wtf was wrong with it in the original actor and ye that seems to be the case.

**Comment by MrPrimate** [comment]
Cool, are you happy for me to close this issue?
