### ISSUE TITLE
Error: An error occurred while rendering DDBMuncher ##. Cannot read properties of undefined (reading 'sources')

### ISSUE THREAD

**Issue by WardenOfSecrets** [MrPrimate/ddb-importer#533]
**The bug**

**How To Reproduce**
1. Go to Configure Game Settings
2. Click on Core setup
3. Enter Cobalt Cookie
4. DB Muncher button in compendiums no longer works, (Does not prompt the Core settings screen)

**Expected behavior**
Opens DB muncher and allows me to import stat blocks, spells, etc

**Screenshots**
![Screenshot 2024-12-30 202541](https://github.com/user-attachments/assets/5e5d38d8-9e8e-4fe6-ba14-3a2126d18172)
Highlighted text in the counsel is the error i get, attempted to enable just DDB muncher module, attempted to uninstall and reinstall foundry. Attempted to remove the module files from %appdata% in the foundry modules directory in there. After removing the cobalt cookie, (Witch comes back with a success BTW when I enter it and check it) I can see the Core set up screen again, which is odd.

**Environment:**
 - Browser [e.g. Edge?] Edge is my default browser. I think foundry uses Chrome? I use the foundry VTT app when doing anything.
 - Foundry Version [e.g. 12.331]
 - 5e System Version [e.g 4.1.2]
 - Module Version [e.g ddb-importer(6.0.58)]

**Error Logs**
Error: An error occurred while rendering DDBMuncher 77. Cannot read properties of undefined (reading 'sources')
[Detected 1 package: ddb-importer(6.0.58)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.js:5795:13

**Character Problem?**

**Disabled Other Modules?**
Attempted and had the **Same Result**

- Have you tried with all other modules disabled?
- Yes, the result was the same

**Additional context**

**Comment by MrPrimate** [comment]
Please can you try with all other modules disabled and provide the error message then? The error message provided is coming from within the lib wrapper, indicating that at least one module is interfering with and overriding core foundry functions.

**Comment by WardenOfSecrets** [comment]
Error: An error occurred while rendering DDBMuncher 27. Cannot read properties of undefined (reading 'sources')
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5795:13
![Screenshot 2024-12-31 110455](https://github.com/user-attachments/assets/5fafdf81-67c5-42df-b161-9c64a6ef6057)

**Comment by WardenOfSecrets** [comment]
Thank you for your time and quick response.
I didn't expect you to reply so quickly.

**Comment by MrPrimate** [comment]
> Error: An error occurred while rendering DDBMuncher 27. Cannot read properties of undefined (reading 'sources')
>     at Hooks.onError (foundry.js:654:24)
>     at foundry.js:5795:13
> ![Screenshot 2024-12-31 110455](https://github.com/user-attachments/assets/5fafdf81-67c5-42df-b161-9c64a6ef6057)
> 

Can you check to make sure your DDB Summons Compendium is created and selected in the DDB Importer Compendiums settings section?

**Comment by WardenOfSecrets** [comment]
They where not set properly, I did so but it still didn't work. Afterwords I cut out the compendium folders from Appdata and it fixed it. Thank you very much for that. Happy new years.
