### ISSUE TITLE
Spell Muncher TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by jwfreeland1** [MrPrimate/ddb-importer#77]
Importer version 0.2.29
FoundryVTT 0.79

Receiving the following error when running the Spell Muncher:

```
DDB Importer | ERR > TypeError: Cannot read property 'name' of undefined
    at http://localhost:30000/modules/ddb-importer/dist/main.js:18382:24
    at Array.map (<anonymous>)
    at parseSpells (http://localhost:30000/modules/ddb-importer/dist/main.js:18381:4)
    at async Function.parseSpells (http://localhost:30000/modules/ddb-importer/dist/main.js:22963:22)
```

Race and Item imports worked fine. I've tried reinstalling it but that didn't fix the issue.

**Comment by MrPrimate** [comment]
Fixed in 0.2.30, sorry for the disruption!
